### PR TITLE
Use real login for Mattermost

### LINKED ISSUE #13: Widget Mattermost: Expired session
It seems that the private token of the Mattermost widget expires after some time.

After seeing the error below I had to take a fresh private token from my session ;)

```
  crasher:
    initial call: Elixir.Neoboard.Widgets.Mattermost:init/1
    pid: <0.26693.0>
    registered_name: []
    exception exit: {{badmatch,
                         {ok,#{'__struct__' => 'Elixir.HTTPoison.Response',
                               body => <<"{\"id\":\"api.context.session_expired.app_error\",\"message\":\"Invalid or expired session, please login again.\",\"detailed_error\":\"\",\"request_id\":\"dxssqffr4brgpewzriscfcepoy\",\"status_code\":401}">>,
                               headers => [{<<"Server">>,<<"nginx">>},
                                {<<"Date">>,
                                 <<"Wed, 23 Nov 2016 13:11:16 GMT">>},
                                {<<"Content-Type">>,<<"application/json">>},
                                {<<"Content-Length">>,<<"186">>},
                                {<<"Connection">>,<<"keep-alive">>},
                                {<<"Expires">>,<<"0">>},
                                {<<"Set-Cookie">>,
                                 <<"MMAUTHTOKEN=; Path=/; Max-Age=0; HttpOnly">>},
                                {<<"X-Ratelimit-Limit">>,<<"10">>},
                                {<<"X-Ratelimit-Remaining">>,<<"9">>},
                                {<<"X-Ratelimit-Reset">>,<<"1">>},
                                {<<"X-Request-Id">>,
                                 <<"dxssqffr4brgpewzriscfcepoy">>},
                                {<<"X-Version-Id">>,
                                 <<"3.3.0.23a426d85705964ff9b5511cc91d7917">>}],
                               status_code => 401}}},
```

/cc @jnbt

### PR DESCRIPTION
**Pull request by jnbt**
Resolves #13

* Don't directly use the expiring private token, instead perform a real login
* Login via email/password or username/password (this is a Mattermost configuration)
* Requires Mattermost own login system to be enabled!
* Automatically re-login when the token expires

/cc @splattael

### CODE REVIEW

File: lib/neoboard/widgets/mattermost.ex [hunk 1]
```diff
@@ -3,34 +3,55 @@ defmodule Neoboard.Widgets.Mattermost do
...
   alias Neoboard.TimeService
+  alias Neoboard.Widgets.Mattermost.Authentication
+  alias Neoboard.Widgets.Mattermost.AuthenticationError
   alias Neoboard.Widgets.Mattermost.Fetcher
 
   def start_link do
     {:ok, pid} = GenServer.start_link(__MODULE__, :ok)
-    send(pid, :tick)
-    :timer.send_interval(config[:every], pid, :tick)
+    send(pid, :login)
```
Comment (splattael) [inline lib/neoboard/widgets/mattermost.ex:11]: Is it ok to send message to the GenServer even `init` has been called?
IMHO, it's safer to use `send(pid, :login)` in `init(:ok)`.

File: lib/neoboard/widgets/mattermost.ex [hunk 2]
```diff
@@ -3,34 +3,55 @@ defmodule Neoboard.Widgets.Mattermost do
...
     {:ok, pid}
   end
 
   def init(:ok) do
-    HTTPoison.start
+    {:ok, %{}}
```
Comment (splattael) [inline lib/neoboard/widgets/mattermost.ex:16]: Use `send(self(), :login)` here (see my comment above).

File: lib/neoboard/widgets/mattermost.ex [hunk 3]
```diff
@@ -3,34 +3,55 @@ defmodule Neoboard.Widgets.Mattermost do
...
+  end
 
-    {:ok, %{
+  def handle_info(:login, _) do
+    {:ok, authentication} = Authentication.login(config)
+    send(self(), :tick)
```
Comment (splattael) [inline lib/neoboard/widgets/mattermost.ex]: I am a bit confused by the message flow here.
Does `handle_info(:tick, state)` happen before or after the new state below has been propagated?

File: lib/neoboard/widgets/mattermost.ex [hunk 4]
```diff
@@ -3,34 +3,55 @@ defmodule Neoboard.Widgets.Mattermost do
...
+    {:noreply, %{
+      private_token: authentication.private_token,
```
Comment (splattael) [inline lib/neoboard/widgets/mattermost.ex]: I meant this state (see comment above)

**Review by splattael — COMMENTED** [review]
I like the solution!

I left some confusing comments ;)

**Review by splattael — APPROVED** [review]
